

store_image_path: "data/02_intermediate/images"



test_data_ratio: 0.2
example_learning_rate: 0.01




train_csv: 'data/04_features/train.csv'
test_csv: 'data/04_features/test.csv'
label_pbtxt: 'data/04_features/label_map.pbtxt'


test_record_fname: 'data/05_model_input/test.record'
train_record_fname: 'data/05_model_input/train.record'
label_map_pbtxt_fname: 'data/04_features/label_map.pbtxt'


train_model: 'ssd_mobilenet_v2_coco_2018_03_29'
download_base: 'http://download.tensorflow.org/models/object_detection/'
store_pre_model: 'data/06_models/'


pipeline_file: 'ssd_mobilenet_v2_coco.config'
num_train_iter: 5000
num_steps: 50

# batch: ${file(./model_config.yml):${MODEL_NAME}.batch_size}

